version: 2
jobs:
  build:
    machine:
      image: ubuntu-2204:edge
    paralleism: 20
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            docker-compose up -d
      - run:
          name: check
          command: |
              docker-compose -f ~/project/docker-compose.yml top redis | head -n1
      - run:
          name: log
          command: docker-compose -f ~/project/docker-compose.yml logs
          when: always
