version: 2
jobs:
  build:
    working_directory: /dockerapp1
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            docker-compose up -d
      - run:
          name: check
          command: |
              docker-compose -f ~/project/dockerapp1/docker-compose.yml top redis | head -n1

