version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            docker-compose up -d
      - run:
          name: check
          command: |
            docker docker-compose -f ~/docker-compose.yml top redis | head -n1
